<NAME>PHP3 Name1</NAME><URL>PHP3 URL1</URL><ICON>PHP3 Icon1</ICON><FANART>PHP3 Fanart1</FANART><DESCRIPTION>PHP3 Description1</DESCRIPTION>
<NAME>PHP3 Name2</NAME><URL>PHP3 URL2</URL><ICON>PHP3 Icon2</ICON><FANART>PHP3 Fanart2</FANART><DESCRIPTION>PHP3 Description2</DESCRIPTION>
<NAME>PHP3 Name3</NAME><URL>PHP3 URL3</URL><ICON>PHP3 Icon3</ICON><FANART>PHP3 Fanart3</FANART><DESCRIPTION>PHP3 Description3</DESCRIPTION>
<NAME>PHP3 Name4</NAME><URL>PHP3 URL4</URL><ICON>PHP3 Icon4</ICON><FANART>PHP3 Fanart4</FANART><DESCRIPTION>PHP3 Description4</DESCRIPTION>
<NAME>PHP3 Name5</NAME><URL>PHP3 URL5</URL><ICON>PHP3 Icon5</ICON><FANART>PHP3 Fanart5</FANART><DESCRIPTION>PHP3 Description5</DESCRIPTION>