<NAME>PHP4 Name1</NAME><URL>PHP4 URL1</URL><ICON>PHP4 Icon1</ICON><FANART>PHP4 Fanart1</FANART><DESCRIPTION>PHP4 Description1</DESCRIPTION>
<NAME>PHP4 Name2</NAME><URL>PHP4 URL2</URL><ICON>PHP4 Icon2</ICON><FANART>PHP4 Fanart2</FANART><DESCRIPTION>PHP4 Description2</DESCRIPTION>
<NAME>PHP4 Name3</NAME><URL>PHP4 URL3</URL><ICON>PHP4 Icon3</ICON><FANART>PHP4 Fanart3</FANART><DESCRIPTION>PHP4 Description3</DESCRIPTION>
<NAME>PHP4 Name4</NAME><URL>PHP4 URL4</URL><ICON>PHP4 Icon4</ICON><FANART>PHP4 Fanart4</FANART><DESCRIPTION>PHP4 Description4</DESCRIPTION>
<NAME>PHP4 Name5</NAME><URL>PHP4 URL5</URL><ICON>PHP4 Icon5</ICON><FANART>PHP4 Fanart5</FANART><DESCRIPTION>PHP4 Description5</DESCRIPTION>